site_name: Tatsu 

repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-Tatsu
edit_uri: ""


theme: 
  name: material
  features: navigation.tabs
  logo: Assets/Images/LogoHorizontal.svg
  favicon: Assets/Images/favicon.ico


extra_css:
  - Assets/Stylesheets/extra.css

nav:
  - Home: "index.md"
  - Visão Unidade 1: "visao.md"
  - Visão Unidade 2: "visao2.md"
  - Visão Unidade 3: "visao3.md"
  - Visão Unidade 4: "visao4.md"
  - Apresentação do Projeto: "apresentacao.md"
  - Requisitos Iniciais: "requisitos_iniciais.md"
  - Kanban: "kanban.md"
  - Canvas MVP: "canvasMVP.md"
  - PBB: "pbb.md"
  - BDD: "bdd.md"
  - USM: "userStoryMap.md"
  - Casos de uso: "userCases.md"
  
markdown_extensions:
  - attr_list