site_name: Tatsu 

repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-Tatsu
edit_uri: ""


theme: 
  name: material
  features: navigation.tabs
  logo: Assets/Images/LogoHorizontal.svg
  favicon: Assets/Images/favicon.ico


extra_css:
  - Assets/Stylesheets/extra.css

nav:
  - Home: "index.md"
  - Visão: "visao.md"
  - Apresentação do Projeto: "apresentacao.md"

markdown_extensions:
  - attr_list