site_name: Tatsu 

repo_url: https://fgaunb-req-gm.github.io/2021.2-Tatsu/
edit_uri: ""


theme: 
  name: material
  features: navigation.tabs


extra_css:
  - Assets/Stylesheets/extra.css

nav:
  - Home: "index.md"

markdown_extensions:
  - attr_list