site_name: Tatsu 

repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Grupo01
edit_uri: ""


theme: 
  name: material
  features: navigation.tabs


extra_css:
  - Assets/Stylesheets/extra.css

nav:
  - Home: "index.md"

markdown_extensions:
  - attr_list