"""empty message

Revision ID: 6dac203f476f
Revises: 
Create Date: 2022-03-30 01:42:37.536766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dac203f476f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('game',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('gameMode', sa.String(), nullable=False),
    sa.Column('timer', sa.Time(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('characterSheet',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('characterName', sa.String(), nullable=True),
    sa.Column('vClass', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('background', sa.String(), nullable=True),
    sa.Column('playerName', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['game.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('gamePlayers',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['game.Id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('message',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gameId'], ['game.Id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Bonus',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.Column('savingThrows', sa.String(), nullable=True),
    sa.Column('proficiencyBonus', sa.Integer(), nullable=True),
    sa.Column('inspiration', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('attacksSpellcasting',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('attackBonus', sa.Integer(), nullable=False),
    sa.Column('damageType', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('attributes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.Column('strenght', sa.Integer(), nullable=True),
    sa.Column('modStrenght', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('modDexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('modConstitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('modIntelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('modWisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('modCharisma', sa.Integer(), nullable=True),
    sa.Column('passiveWisdom', sa.Integer(), nullable=True),
    sa.Column('armorClass', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('maxLife', sa.Integer(), nullable=True),
    sa.Column('currentLife', sa.Integer(), nullable=True),
    sa.Column('lifeDice', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('equipment',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('attunement', sa.String(), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('sp', sa.Integer(), nullable=True),
    sa.Column('ep', sa.Integer(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('playerCharacter',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['gamePlayers.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('skills',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('acrobatics', sa.Integer(), nullable=True),
    sa.Column('animal_Handling', sa.Integer(), nullable=True),
    sa.Column('arcana', sa.Integer(), nullable=True),
    sa.Column('athletics', sa.Integer(), nullable=True),
    sa.Column('deception', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('insight', sa.Integer(), nullable=True),
    sa.Column('intimidation', sa.Integer(), nullable=True),
    sa.Column('investigation', sa.Integer(), nullable=True),
    sa.Column('medicine', sa.Integer(), nullable=True),
    sa.Column('nature', sa.Integer(), nullable=True),
    sa.Column('perception', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('persuasion', sa.Integer(), nullable=True),
    sa.Column('religion', sa.Integer(), nullable=True),
    sa.Column('sleight_of_hand', sa.Integer(), nullable=True),
    sa.Column('stealth', sa.Integer(), nullable=True),
    sa.Column('survival', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('strokes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('characterSheetId', sa.Integer(), nullable=True),
    sa.Column('personalityTraits', sa.String(), nullable=True),
    sa.Column('ideals', sa.String(), nullable=True),
    sa.Column('bonds', sa.String(), nullable=True),
    sa.Column('flaws', sa.String(), nullable=True),
    sa.Column('otherProeficienciesLanguages', sa.String(), nullable=True),
    sa.Column('featuresTraits', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characterSheetId'], ['characterSheet.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strokes')
    op.drop_table('skills')
    op.drop_table('playerCharacter')
    op.drop_table('equipment')
    op.drop_table('attributes')
    op.drop_table('attacksSpellcasting')
    op.drop_table('Bonus')
    op.drop_table('message')
    op.drop_table('gamePlayers')
    op.drop_table('characterSheet')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
